apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: alloy
      version: "1.6.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
  valuesFrom:
    - kind: ConfigMap
      name: alloy-values-override
      optional: true
  values:
    controller:
      type: 'daemonset'
      rbac:
        create: true
    alloy:
      clustering:
        enabled: false
      resources:
        limits:
          cpu: null
          memory: 256Mi
      extraEnv:
        - name: GOMEMLIMIT
          value: "75MiB"
        - name: GOGC
          value: "50"
      configMap:
        content: |-
          logging {
            level  = "info"
            format = "logfmt"
          }

          livedebugging {
            enabled = false
          }

          prometheus.operator.servicemonitors "node_only" {
            selector {
              selector {
                match_expression {
                  key      = "app.kubernetes.io/name"
                  operator = "In"
                  values   = ["prometheus-node-exporter", "kubelet"]
                }
              }
            }
            forward_to = [prometheus.relabel.node_local_filter.receiver]
          }

          prometheus.relabel "node_local_filter" {
            forward_to = [prometheus.relabel.drop_high_cardinality.receiver]
            rule {
              action        = "keep"
              source_labels = ["__meta_kubernetes_pod_node_name"]
              regex         = sys.env("NODE_NAME")
            }
          }

          prometheus.relabel "drop_high_cardinality" {
            forward_to = [prometheus.remote_write.mimir.receiver]
            rule {
              action        = "drop"
              source_labels = ["__name__"]
              regex         = "(container_tasks_state|container_memory_failures_total|container_blkio_device_usage_total|container_fs_reads_merged_total|container_fs_writes_merged_total|container_cpu_cfs_throttled_periods_total|go_gc_.*|go_memstats_.*)"
            }
          }

          prometheus.remote_write "mimir" {
            endpoint {
              url = "http://obs-sandbox-mimir-gateway.observability/api/v1/push"
              headers = {
                "X-Scope-OrgID" = "INFRA-2", 
              }
              queue_config {
                capacity             = 500
                max_samples_per_send = 500
                max_shards           = 10
              }
            }

            wal {
              truncate_frequency = "1m"
            }
          }