apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-kube-stack
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: opentelemetry-kube-stack
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
  values:
    opentelemetry-operator:
      manager:
        collectorImage:
          repository: otel/opentelemetry-collector-contrib
    kubeStateMetrics:
      enabled: true
    collectors:
      daemon:
        config:
          exporters:
            debug: {}
            prometheus_remote_write:
              endpoint: "http://metrics-new.posindonesia.deploy-at.my.id/metrics/api/v1/push"
              headers:
                "X-Scope-OrgID": "INFRA-Production"
              external_labels:
                cluster: "Sandbox-cluster"
                cloud: "onprem"
                environment: "sandbox"
                region: "us-east-1"
                source: "node-agent"
              remote_write_queue:
                queue_size: 500           # Mirrors capacity
                num_consumers: 10
          # Pipelines
          service:
            pipelines:
              metrics:
                exporters:
                  - debug
                  - prometheus_remote_write