apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: demo
  namespace: monitoring
spec:
  mode: daemonset
  image: otel/opentelemetry-collector-contrib:0.160.0
  targetAllocator:
    enabled: true
    allocationStrategy: per-node
    serviceAccount: alloy
    prometheusCR:
      enabled: true
      podMonitorSelector: 
        matchLabels:
          release: kube-prometheus-stack
      serviceMonitorSelector: 
        matchLabels:
          release: kube-prometheus-stack
  ports:
    - name: zpages
      port: 55679
      targetPort: 55679
      protocol: TCP
  config:
    extensions:
      zpages:
        endpoint: 0.0.0.0:55679

    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector'
              scrape_interval: 10s
              static_configs:
                - targets: ['0.0.0.0:8888']
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
    exporters:
      debug:
        verbosity: detailed
      prometheus_remote_write:
        endpoint: "http://metrics-new.posindonesia.deploy-at.my.id/metrics/api/v1/push"
        headers:
          "X-Scope-OrgID": "INFRA-Production"
        external_labels:
          cluster: "Sandbox-cluster"
          cloud: "onprem"
          environment: "sandbox"
          region: "us-east-1"
          source: "node-agent"
        remote_write_queue:
          queue_size: 500           # Mirrors capacity
          num_consumers: 10          # Mirrors max_shards

    service:
      extensions: [zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter]
          exporters: [debug]
        metrics:
          receivers: [otlp, prometheus]
          processors: [memory_limiter]
          exporters: [debug, prometheus_remote_write]
        logs:
          receivers: [otlp]
          processors: [memory_limiter]
          exporters: [debug]
