apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: telegram-alert
  namespace: flux-system
spec:
  summary: "🚨 [sandbox-cluster | sandbox]"
  eventMetadata:
    env: sandbox
    cluster: sandbox-cluster
    region: us-east-1