apiVersion: v1
kind: Secret
metadata:
  name: alloy-service-account-token
  namespace: monitoring
  annotations:
    kubernetes.io/service-account.name: alloy
type: kubernetes.io/service-account-token