apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/notification-infra-team
  - ../../base/argocd
  - non-existent-file.yaml # <--- Will cause Kustomize build failure

# Strategic merge patch to apply production HA values over the base HelmRelease
patches:
  - path: argocd-values-patch.yaml
    target:
      kind: HelmRelease
      name: argocd
      namespace: argocd
  - path: alert-eventmetadata-patch.yaml
    target:
      kind: Alert
      name: telegram-alert
      namespace: flux-system
  - path: provider-summary-patch.yaml
    target:
      kind: Provider
      name: telegram-notifier
      namespace: flux-system