- op: add
  path: /spec/values/kubelet
  value:
    serviceMonitor:
      authorization:
        type: Bearer
        credentials:
          name: alloy-service-account-token
          key: token
- op: add
  path: /spec/values/kubeProxy
  value:
    serviceMonitor:
      authorization:
        type: Bearer
        credentials:
          name: alloy-service-account-token
          key: token